jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Navigate to the correct directory and install dependencies
    - name: Install Dependencies
      working-directory: s.o.u-ata  # Navigate into the project folder
      run: npm install

    # Step 4: Build the project
    - name: Build the Project
      working-directory: s.o.u-ata  # Navigate into the project folder
      run: npm run build

    # Step 5: Verify build directory exists
    - name: Verify Build Directory
      working-directory: s.o.u-ata  # Navigate into the project folder
      run: ls -la build/

    # Step 6: Deploy via FTP
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: s.o.u-ata/build/  # Correct path to build directory
        server-dir: ${{ secrets.FTP_PATH }}
